version: '3'
 
services:
  app:
    build:
      context: .
    command: mix phx.server
    environment:
      DB_HOST: mysql
    links:
      - mysql
    ports:
      - 4000:4000
    volumes:
      - ./everyday_app:/app
    working_dir: /app
    tty: true
    stdin_open: true

  mysql:
    platform: linux/x86_64
    image: ${DOCKER_MYSQL_IMAGE:-mysql:5.7.28}
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - mysql:/var/lib/mysql
    ports:
      - '23306:3306'
volumes:
  mysql: